// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjhjzpaueepujejnuqvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaGp6cGF1ZWVwdWplam51cXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzQ1MTEsImV4cCI6MjA2NDkxMDUxMX0.lRamoNbEIXP5m72MhJiiNwPeXse_Piz77bjH21oc0_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);